path: dataset  # dataset root dir
train: train/images  # train images (relative to 'path')
val: valid/images  # val images (relative to 'path')

# Classes
nc: 1  # number of classes
names: ['door']  # class names

# Classes are automatically loaded from classes.txt files in train/labels/ and valid/labels/
